apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/thanhdinh01/demo-jenkins.git
    targetRevision: HEAD
    path: src
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      prune: true
